### ISSUE TITLE
Feature request - YAML examples

### ISSUE THREAD

**Issue by zalmane** [simonwalz/jsonschema2mk#4]
I plan to use the module for generating markdown of a configuration file schema. The configuration file is YAML based so would be good to be able to pass a flag to generate the "examples" section as yaml markdown and notation, rather than json.
Is it possible to add this functionality?

**Comment by simonwalz** [comment]
Good feature request.

I added it as an extension (see [README.md](https://github.com/simonwalz/jsonschema2mk#readme) and directory [extensions](https://github.com/simonwalz/jsonschema2mk/tree/master/extensions)).

You can call it via:

```sh
npx jsonschema2mk --schema schema.json --extension yaml-examples >DOC.md
```

See [this example](https://github.com/simonwalz/jsonschema2mk/blob/master/test/010-example-artnet-yaml.md).

Does this meet your requirements?

(Added in 3018457587f08e7a1cd35cb0f3db76143f2d51a0)

**Comment by zalmane** [comment]
This is great! Thanks for the quick reply.
